import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Provider";

const inter = Poppins({
	subsets: ["latin"],
	preload: true,
	adjustFontFallback: true,
	weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`bg-[#121213] ${inter.className} min-h-screen w-full`}>
				<div className="fixed top-28 md:-top-10 skew-y-12 skew-x-12 -right-60 md:right-28 h-96 md:h-[770px] rounded-full w-full md:w-[470px] bg-gradient-radial bg-blend-multiply blur-3xl opacity-10" />
				<div className="fixed -bottom-72 md:-bottom-96 skew-y-12 skew-x-12 -left-60 md:-left-14 h-96 md:h-[770px] rounded-full w-full md:w-[470px] bg-gradient-radial bg-blend-multiply blur-3xl opacity-10" />

				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
