import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Provider";
import { Image } from "@nextui-org/react";
// import Image from "next/image";

const inter = Poppins({
	subsets: ["latin"],
	preload: true,
	adjustFontFallback: true,
	weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`bg-[#040404] ${inter.className} w-full h-full antialiased selection:bg-purple-500/90`}>
				<div className="fixed block opacity-70 top-[15%] -right-[60%] sm:-top-[45%] sm:-right-[60%] 2xl:-top-[60%] 2xl:-right-[35%] z-0 rotate-180 sm:scale-y-105 pointer-events-none">
					<Image
						src="/docs-right.png"
						height="100%"
						className="relative z-0 opacity-0 shadow-black/5 data-[loaded=true]:opacity-100 shadow-none transition-transform-opacity motion-reduce:transition-none !duration-300 rounded-large pointer-events-none"
						alt="docs right background"
						data-loaded="true"
					/>
				</div>
				<svg
					className="pointer-events-none fixed isolate z-50 opacity-70 mix-blend-soft-light"
					width="100%"
					height="100%">
					<filter id="pedroduarteisalegend">
						<feTurbulence
							type="fractalNoise"
							baseFrequency="0.80"
							numOctaves="4"
							stitchTiles="stitch"></feTurbulence>
					</filter>
					<rect
						width="100%"
						height="100%"
						filter="url(#pedroduarteisalegend)"></rect>
				</svg>

				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
